[pytest]
addopts = -vv -rsx --cov=tests --cov=delegable --tb=short --flake8 --cov-fail-under=100 --cov-report=term-missing
testpaths = tests
describe_prefixes = describe with without when its

[coverage:run]
source = apscheduler

[coverage:report]
show_missing = true

[flake8]
max-line-length = 99
exclude = .tox,build,docs
